// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "students.hpp"
#include "dob.hpp"
#include "main.hpp"

TEST_CASE("Ex1 ", "[example]")
{
	string sname = "John";
	int idnum = 1001;
	DOB date(12, 24);
	Student s(sname, idnum, date);
	// s = Student();

	s.printStudent();
	cout << "Student Name: " << s.getSname() << endl;
	cout << "Student ID: " << s.getID() << endl;
	date = s.getDOB();
	date.printDate();

	date.setDOB(1, 1);
	REQUIRE(s.getID() == 1001);
	REQUIRE(date.getDay() == 1);
	REQUIRE(date.getMonth() == 1);
	s.setDOB(date);
	date = s.getDOB();
	date.printDate();
	s.printStudent();
}

TEST_CASE("Ex2 ", "[example]")
{
	Student s[10];
	DOB dob;

	fillout(s);
	sortStudent(s);
	REQUIRE(s[0].getID() == 10009999);
	dob = s[0].getDOB();
	REQUIRE(dob.getDay() == 31);
	REQUIRE(dob.getMonth() == 1);
	REQUIRE(s[9].getID() == 10001111);
	dob = s[9].getDOB();
	REQUIRE(dob.getDay() == 24);
	REQUIRE(dob.getMonth() == 12);
}
